title: "HoX Bio Tools Demo"
description: "A getting started guide for the command line and graphical tools provided by the HoX Platform"
markdown: GFM
plugins:
  - jekyll-gfm-admonitions
  - jekyll-github-metadata